<?php
    echo json_encode('<li><a rel="mediaGroup" href="https://www.youtube.com/embed/wFSd5RHGGcM" class="fancybox fancybox.iframe" title="Trailer Võ Lâm Chi Mộng 2"><img src="//mvportal.zing.vn/img/image.php?width=462&amp;height=290&amp;url=http://img.zing.vn/upload/aojian2/source/Gallery/thumbnail.jpg" title="Trailer Võ Lâm Chi Mộng 2" alt="Trailer Võ Lâm Chi Mộng 2" /><h3>Trailer Võ Lâm Chi Mộng 2</h3></a></li>

        <li class="dndmom__photoswipe" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject"><a itemprop="contentUrl" rel="mediaGroup" href="http://img.zing.vn/upload/aojian2/source/Gallery/wall3.jpg" class="key-features__fancybox fancybox fancybox.image"><img src="//mvportal.zing.vn/img/image.php?width=462&amp;height=290&amp;url=http://img.zing.vn/upload/aojian2/source/Gallery/wall3.jpg" itemprop="thumbnail" title="Đào Hoa" alt="Đào Hoa" width="462" height="290" /><h3>Đào Hoa</h3></a></li>

        <li class="dndmom__photoswipe" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject"><a itemprop="contentUrl" rel="mediaGroup" href="http://img.zing.vn/upload/aojian2/source/Gallery/wall4.jpg" class="key-features__fancybox fancybox fancybox.image"><img src="//mvportal.zing.vn/img/image.php?width=462&amp;height=290&amp;url=http://img.zing.vn/upload/aojian2/source/Gallery/wall4.jpg" itemprop="thumbnail" title="Đào Hoa" alt="Đào Hoa" width="462" height="290" /><h3>Tiêu Dao</h3></a></li>

       <li class="dndmom__photoswipe" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject"><a itemprop="contentUrl" rel="mediaGroup" href="http://img.zing.vn/upload/aojian2/source/Gallery/wall2.jpg" class="key-features__fancybox fancybox fancybox.image"><img src="//mvportal.zing.vn/img/image.php?width=462&amp;height=290&amp;url=http://img.zing.vn/upload/aojian2/source/Gallery/wall2.jpg" itemprop="thumbnail" title="Đào Hoa" alt="Đào Hoa" width="462" height="290" /><h3>Cái Bang</h3></a></li>

        <li class="dndmom__photoswipe" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject"><a itemprop="contentUrl" rel="mediaGroup" href="http://img.zing.vn/upload/aojian2/source/Gallery/wall1.jpg" class="key-features__fancybox fancybox fancybox.image"><img src="//mvportal.zing.vn/img/image.php?width=462&amp;height=290&amp;url=http://img.zing.vn/upload/aojian2/source/Gallery/wall1.jpg" itemprop="thumbnail" title="Đào Hoa" alt="Đào Hoa" width="462" height="290" /><h3>Toàn Chân</h3></a></li>

       <li class="dndmom__photoswipe" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject"><a itemprop="contentUrl" rel="mediaGroup" href="http://img.zing.vn/upload/aojian2/source/Gallery/THIET SA CHUONG 2 copy.jpg" class="key-features__fancybox fancybox fancybox.image"><img src="//mvportal.zing.vn/img/image.php?width=462&amp;height=290&amp;url=http://img.zing.vn/upload/aojian2/source/Gallery/THIET SA CHUONG 2 copy.jpg" itemprop="thumbnail" title="Thiết Sa Chưởng" alt="Thiết Sa Chưởng" width="462" height="290" /><h3>Thiết Sa Chưởng</h3></a></li>

        <li class="dndmom__photoswipe" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject"><a itemprop="contentUrl" rel="mediaGroup" href="http://img.zing.vn/upload/aojian2/source/Gallery/HANG LONG THAP BAT CHUOGN 3 copy.jpg" class="key-features__fancybox fancybox fancybox.image"><img src="//mvportal.zing.vn/img/image.php?width=462&amp;height=290&amp;url=http://img.zing.vn/upload/aojian2/source/Gallery/HANG LONG THAP BAT CHUOGN 3 copy.jpg" itemprop="thumbnail" title="Thiết Sa Chưởng" alt="Thiết Sa Chưởng" width="462" height="290" /><h3>Hàng Long Chưởng</h3></a></li>

        <li class="dndmom__photoswipe" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject"><a itemprop="contentUrl" rel="mediaGroup" href="http://img.zing.vn/upload/aojian2/source/Gallery/HANG LONG THAP BAT CHUOGN 3 copy.jpg" class="key-features__fancybox fancybox fancybox.image"><img src="//mvportal.zing.vn/img/image.php?width=462&amp;height=290&amp;url=http://img.zing.vn/upload/aojian2/source/Gallery/HANG LONG THAP BAT CHUOGN 3 copy.jpg" itemprop="thumbnail" title="Thiết Sa Chưởng" alt="Thiết Sa Chưởng" width="462" height="290" /><h3>Đấu Chuyển Tinh Di</h3></a></li>

        <li class="dndmom__photoswipe" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject"><a itemprop="contentUrl" rel="mediaGroup" href="http://img.zing.vn/upload/aojian2/source/Gallery/HANG LONG THAP BAT CHUOGN 3 copy.jpg" class="key-features__fancybox fancybox fancybox.image"><img src="//mvportal.zing.vn/img/image.php?width=462&amp;height=290&amp;url=http://img.zing.vn/upload/aojian2/source/Gallery/HANG LONG THAP BAT CHUOGN 3 copy.jpg" itemprop="thumbnail" title="Thiết Sa Chưởng" alt="Thiết Sa Chưởng" width="462" height="290" /><h3>Bích Ba Chưởng Pháp</h3></a></li>

        <li class="dndmom__photoswipe" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject"><a itemprop="contentUrl" rel="mediaGroup" href="http://img.zing.vn/upload/aojian2/source/Gallery/HANG LONG THAP BAT CHUOGN 3 copy.jpg" class="key-features__fancybox fancybox fancybox.image"><img src="//mvportal.zing.vn/img/image.php?width=462&amp;height=290&amp;url=http://img.zing.vn/upload/aojian2/source/Gallery/HANG LONG THAP BAT CHUOGN 3 copy.jpg" itemprop="thumbnail" title="Thiết Sa Chưởng" alt="Thiết Sa Chưởng" width="462" height="290" /><h3>Ngọc Dương Thần Công</h3></a></li>

        <input type="hidden" id="itemTotal" value="14" ><input type="hidden" id="itemPerPage" value="10" ><input type="hidden" id="shortUri" value="http://mvportal.zing.vn/thu-vien/" ><input type="hidden" id="currentSection" value="danh-sach" ><input type="hidden" id="section" value="thu-vien" >');
?>